### ISSUE TITLE
masked to nan error when producing a hopgraph

### ISSUE THREAD

**Issue by iwelland** [iwelland/hop#1]
The hop-generate-hopgraph.py script also generates plots of S(t) fits. However lately it has been producing the following stack:
/usr/local/lib/python2.7/dist-packages/numpy/ma/core.py:3900: UserWarning: Warning: converting a masked element to nan.
  warnings.warn("Warning: converting a masked element to nan.")
Traceback (most recent call last):
  File "/usr/local/bin/hop-generate-hopgraph.py", line 6, in <module>
    exec(compile(open(**file**).read(), **file**, 'exec'))
  File "/tmp/src/hop/scripts/hop-generate-hopgraph.py", line 117, in <module>
    analyze_hopgraph(density, opts.output)
  File "/tmp/src/hop/scripts/hop-generate-hopgraph.py", line 50, in analyze_hopgraph
    hop.interactive.hopgraph_basic_analysis(h, density, filename)
  File "/tmp/src/hop/hop/interactive.py", line 531, in hopgraph_basic_analysis
    h.plot_fits(directory=survival_time_dir, ncol=2, nrow=3)
  File "/tmp/src/hop/hop/graph.py", line 956, in plot_fits
    fig.savefig(filename)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 1476, in savefig
    self.canvas.print_figure(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 2211, in print_figure
    *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 521, in print_png
    FigureCanvasAgg.draw(self)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 469, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 1085, in draw
    func(_args)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 2110, in draw
    a.draw(renderer)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axis.py", line 1119, in draw
    tick.draw(renderer)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axis.py", line 249, in draw
    self.label1.draw(renderer)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/text.py", line 642, in draw
    ismath=ismath, mtext=mtext)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 187, in draw_text
    return self.draw_mathtext(gc, x, y, s, prop, angle)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 177, in draw_mathtext
    y = np.round(y - oy + yd)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2648, in round_
    return round(decimals, out)
  File "/usr/local/lib/python2.7/dist-packages/numpy/ma/core.py", line 4903, in round
    result._mask = self._mask
AttributeError: 'numpy.float64' object has no attribute '_mask'

I suspect this is a dependency issue since I have updated numpy and matplotlib since work began on hop, but I have not fixed it. The issue does not prevent data generation so the process can mostly proceed smoothly but it should be taken care of.

**Comment by iwelland** [comment]
The command used to generate it was 

 hop-generate-hopgraph.py -s hoptraj.psf -f hoptraj.dcd water.pickle

Note that the pickle file was remapped from 1.7 to 1.4 using map_sites, which recently received a minor update to coincide with the new networkx. Probably not the source but this should be checked on non-remapped densities just in case.
